import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Self-hosted Futura PT from public/font (paths resolve relative to this file)
const futura = localFont({
  variable: "--font-futura",
  display: "swap",
  src: [
    { path: "../public/font/FuturaPT-Light.woff2", weight: "300", style: "normal" },
    { path: "../public/font/FuturaPT-LightObl.woff2", weight: "300", style: "italic" },
    { path: "../public/font/FuturaPT-Book.woff2", weight: "400", style: "normal" },
    { path: "../public/font/FuturaPT-BookObl.woff2", weight: "400", style: "italic" },
    { path: "../public/font/FuturaPT-Medium.woff2", weight: "500", style: "normal" },
    { path: "../public/font/FuturaPT-MediumObl.woff2", weight: "500", style: "italic" },
    { path: "../public/font/FuturaPT-Demi.woff2", weight: "600", style: "normal" },
    { path: "../public/font/FuturaPT-Bold.woff2", weight: "700", style: "normal" },
    { path: "../public/font/FuturaPT-BoldObl.woff2", weight: "700", style: "italic" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${futura.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
